name: CI

on:
  push:
    paths-ignore:
      - '.gitignore'
      - '**/*.md'
      - 'assets/**'

  pull_request:
    paths-ignore:
      - '.gitignore'
      - '**/*.md'
      - 'assets/**'

  workflow_dispatch:

jobs:
  build:
    name: Build tvOS Rootful
    runs-on: macos-14

    env:
      THEOS: ~/theos

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app

      - name: Show SDKs
        run: |
          xcodebuild -showsdks

      - name: Set up Procursus
        uses: beerpiss/procursus-action@v2
        with:
          packages: ldid xz-utils cmark make perl git
          cache: true
          cache-path: ~/__cache

      - name: Set up Theos
        run: |
          git clone --recursive --depth=1 https://github.com/theos/theos.git ~/theos

      - name: Build Package
        id: package_build
        run: |
          gmake clean package FINALPACKAGE=1

          PACKAGE=$(find packages -name "*.deb" | head -n 1)

          echo "package=$PACKAGE" >> $GITHUB_OUTPUT

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: NewTerm-tvOS-rootful
          path: ${{ steps.package_build.outputs.package }}
